---
# tasks file for nginx
- name: Install nginx
  yum:
    name: 'nginx'
    state: 'latest'
  notify: start nginx

- name: Create web directory
  file:
    path: /var/www
    state: directory
    mode: '0755'

- name: Create index.html
  template:
    src: index.html.j2
    dest: /var/www/index.html

- name: Configure nginx
  template:
    src: site.conf.j2
    dest: /etc/nginx/conf.d/site.conf
  notify: restart nginx
